# Generated by Django 4.2.5 on 2023-09-26 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('balance', models.FloatField(default=0)),
                ('maturity', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'checking'), (1, 'savings'), (2, 'money_market'), (3, 'CD')])),
                ('min_deposit', models.FloatField()),
                ('min_balance', models.FloatField()),
                ('maintenance_fee', models.FloatField()),
                ('overdraft_fee', models.FloatField()),
                ('apy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='bank.account')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='bank.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bank.accounttype'),
        ),
    ]
