# Generated by Django 4.2.5 on 2023-09-27 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='maturity_period',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='apy',
            field=models.FloatField(default=0),
        ),
    ]
