# Generated by Django 4.2.5 on 2023-09-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_accounttype_maturity_period_alter_accounttype_apy'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
