# Generated by Django 4.2.5 on 2023-09-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
