# Generated by Django 4.2.5 on 2023-09-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
