# Generated by Django 4.2.5 on 2023-09-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_remove_account_number_remove_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='maturity',
            field=models.DateField(default=0),
        ),
    ]
