# Generated by Django 4.2.5 on 2023-09-29 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_alter_transaction_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='maturity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='bank.account'),
        ),
    ]
