# Generated by Django 4.2.5 on 2023-10-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='maintenance_fee',
            field=models.DecimalField(decimal_places=2, max_digits=28),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='min_balance',
            field=models.DecimalField(decimal_places=2, max_digits=28),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='min_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=28),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='overdraft_fee',
            field=models.DecimalField(decimal_places=2, max_digits=28),
        ),
    ]
